config/routes.rb
Rails.application.routes.draw do
  root to: 'tools#index'

  namespace :admin do
    resources :categories
  end

  resources :categories, only: [:show]

  resources :tools

  resources :user, only: [:edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true, uniqueness: { scope: :name }
  validates :quantity, presence: true

  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true

  has_many :tools

  enum role: %w(default, admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category '#{@category.name}' successfully created!"
      redirect_to admin_category_path(@category)
    else
      flash.now[:error] = "#{@category.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Category #{@category.name} removed successfully"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool, :current_tool_summary, :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def most_recent_tool
    unless current_admin?
      @most_recent_tool ||= current_user.tools.find(session[:most_recent_tool_id]) if session[:most_recent_tool_id] && current_user
    end
  end

  def current_tool_summary
    if session[:most_recent_tool_id]
      "#{session[:current_tool_count]} new tools added this session,
      worth a total of $#{session[:current_potential_revenue]}"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = user_tools_in_category
  end

  private

  def user_tools_in_category
    category = Category.find(params[:id])
    current_user.tools.where(category: category)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to tools_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:success] = "Successfully logged out"
    redirect_to root_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      flash[:notice] = "#{@tool.name} successfully stored!"
      session[:most_recent_tool_id] = @tool.id
      session[:current_tool_count] = session[:current_tool_count].to_i + 1
      session[:current_potential_revenue] = session[:current_potential_revenue].to_f + (@tool.price * @tool.quantity)
      redirect_to @tool
    else
      flash.now[:error] = "#{@tool.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def new
    @tool = Tool.new
  end

  def edit
    @tool = tool_for_page
  end

  def show
    @tool = tool_for_page
  end

  def update
    @tool = tool_for_page
    if @tool.update_attributes(tool_params)
      redirect_to @tool
    else
      render :edit
    end
  end

  def destroy
    @tool = tool_for_page
    @tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price, :category_id, :user_id)
  end

  def tool_for_page
    Tool.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully updated account"
      redirect_to tools_path
    else
      flash.now[:error] = "#{@user.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
  def categories
    Category.all.map { |cat| [cat.name, cat.id] }
  end
end

app/helpers/user_helper.rb
module UserHelper
  def default_users
    User.all.where(role: 'default').map { |user| [user.username, user.id] }
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.submit %>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit <%= @category.name %></h1>
<%= render partial: "form" %>

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <%= link_to category.name, admin_category_path(category) %>
  <% end %>
</ul>

<%= link_to "Create New Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>Create New Category</h1>
<%= render partial: "form" %>

app/views/admin/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= link_to "Edit", edit_admin_category_path(@category) %>
<%= link_to "Delete", admin_category_path(@category), method: :delete %>

app/views/categories/show.html.erb
<h1>Tools in Category '<%= @category.name %>'</h1>
<ul>
  <% @category.each do |tool| %>
    <li><%= link_to tool.name, tool %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "flash-#{type}" %>
  <% end %>

  <% if current_user %>
    <p><strong>Welcome, <%= current_user.username %>!</strong></p>
    <p><%= link_to "Logout", logout_path, method: :delete %> <%= link_to "Edit User", edit_user_path(current_user) %></p>
  <% else %>
    <p><%= link_to "Login", login_path %></p>
  <% end %>

  <% if most_recent_tool %>
    <p><strong>Newest tool:</strong> <%= most_recent_tool.name %></p>
    <p><strong>Current Sessions Tool Summary:</strong> <%= current_tool_summary %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/tools/_list.html.erb
<table>
  <thead>
    <th>
      Name
    </th>
    <th>
      Price
    </th>
    <th>
      Quantity
    </th>
    <th>
      Category
    </th>
  </thead>
  <tbody>
    <% if current_user %>
      <% current_user.tools.each do |tool| %>
      <tr>
        <td>
          <%= link_to tool.name, tool_path(tool.id) %>
        </td>
        <td>
          <%= tool.price %>
        </td>
        <td>
          <%= tool.quantity %>
        </td>
        <% if tool.category %>
          <td>
            <%= link_to tool.category.name, category_path(tool.category) %>
          </td>
        <% end %>
      </tr>
      <% end %>
    <% else %>
      <% target.each do |tool| %>
        <tr>
          <td>
            <%= link_to tool.name, tool %>
          </td>
          <td>
            <%= tool.price %>
          </td>
          <td>
            <%= tool.quantity %>
          </td>
          <% if tool.category %>
            <td>
              <%= tool.category.name %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tools/_tool_form.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :price %>:
  <%= f.text_field :price %><br />

  <%= f.label :quantity %>:
  <%= f.number_field :quantity %><br />

  <%= f.label :category_id %>
  <%= f.select :category_id, categories %><br />

  <% if current_admin? %>
    <%= f.label :user_id %>
    <%= f.select :user_id, default_users %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<h1>Edit <%= @tool.name %></h1>
<%= render "tool_form" %>

app/views/tools/index.html.erb
<h1>All Tools</h1>
<%= render partial: "list", locals: { target: @tools } %>

<p><%= link_to "Create New Tool", new_tool_path %></p>

app/views/tools/new.html.erb
<h1>Create a New Tool</h1>
<%= render "tool_form" %>

app/views/tools/show.html.erb
<h1>Product Details for <%= @tool.name %></h1>
<%= render partial: "list", locals: { target: [@tool] } %>

<p><%= link_to "Edit Tool", edit_tool_path(@tool) %></p>
<p><%= link_to "Delete Tool", tool_path(@tool), method: 'DELETE' %></p>
<p><%= link_to "Back to All Tools", tools_path %>

app/views/user/edit.html.erb
<h1>Edit <%= @user.username %></h1>
<p>
  Please enter a new username and/or password
</p>
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br />

  <%= f.label :password %>
  <%= f.password_field :password %><br />

  <%= f.submit %>
<% end %>